oblador/react-native-vector-icons

package.json
Icons show fine on my app with 0.11.0-rc. Thanks!
=> React Native 0.11.0-rc

lib/create-icon-set.js, package.json
I made the change you suggested to use parts of lodash from the main lodash package instead of requiring separate packages for each function.
=> Only include the bits of lodash that are actually needed

README.md, index.js, lib/create-icon-set-from-icomoon.js
Similar than fontello support, this PR allow to load icomoon font-map templates.
=> Support icomoon template-fonts

README.md
To avoid issues similar to #252 in the future.
=> Update README to clarify IcoMoon setup

README.md
Because it works :)
(I use this because I share code with RN & [react-native-web](https://github.com/necolas/react-native-web))
=> Add instructions to consume this library on the web with webpack

templates/bundled-icon-set.tpl, templates/separated-icon-set.tpl
Fixes #340 
Not sure if you want me to update the generated files as well. Please tell me if this needs more work, I'm happy to do it.
=> Update templates to export Button

README.md
Following a comment I got on react-native-web repo.
=> README: update web/webpack setup notes

RNVectorIcons.xcodeproj/project.pbxproj
This is required to use the library on tvOS
=> Add tvOS target

README.md
Added a react native netflix app to community examples.
=> Updated Readme with a Community Example

README.md
tried to make a more clear separation of terms
=> updated emphasis

android/src/main/java/com/oblador/vectoricons/VectorIconsPackage.java
=> Remove override of createJSModules

Examples/IconExplorer/IconList.js, Examples/IconExplorer/IconSetList.js, Examples/IconExplorer/index.android.js, Examples/IconExplorer/index.ios.js, Examples/IconExplorer/index.osx.js, Examples/IconExplorer/index.windows.js, Examples/TabBarExample/index.ios.js, RNIMigration.js, directory/src/App.js, lib/create-icon-set.js, lib/icon-button.js, lib/tab-bar-item-ios.js, lib/toolbar-android.js
=> Use PureComponent instead of Component

Examples/IconExplorer/IconSetList.js
I discover an issue when was trying to build and run IconExplorer app. This pull request is aimed to fix the issue.
=> Fix keyboard dismiss in IconExplorer

android/build.gradle
just a little improved version rather then many explicit def for each value.
=> little improvement over too many "def"

lib/create-icon-set-from-icomoon.js
The IconMoon may have few names for the same icon. Like "spinner, loader, wait"
=>  IconMoon Aliases

directory/src/App.js
This method is never called by anything
=> removing unused class method in App.js

README.md
Add list of all fonts to copy & paste in the info.plist file
=> Add list of all fonts to copy & paste in the info.plist file

fonts.gradle
Fixes #959 
Solution in [PR 913](https://github.com/oblador/react-native-vector-icons/pull/913) was correct, just needed to reapply changes / fix merge conflicts.
=> fixed gradle copy font tasks when using variants

lib/react-native.web.js
Fixes the default export issues caused by 0.11.[x]
=> Added support for React-Native Web 0.11

Examples/IconExplorer/.babelrc, Examples/IconExplorer/.gitignore, Examples/IconExplorer/android/app/BUCK, Examples/IconExplorer/android/app/build.gradle, Examples/IconExplorer/android/app/build_defs.bzl, Examples/IconExplorer/android/app/src/debug/AndroidManifest.xml, Examples/IconExplorer/android/app/src/main/AndroidManifest.xml, Examples/IconExplorer/android/app/src/main/java/com/iconexplorer/MainApplication.java, Examples/IconExplorer/android/build.gradle, Examples/IconExplorer/android/gradle/wrapper/gradle-wrapper.properties, Examples/IconExplorer/android/settings.gradle, Examples/IconExplorer/babel.config.js, Examples/IconExplorer/index.android.js, Examples/IconExplorer/ios/IconExplorer-tvOS/Info.plist, Examples/IconExplorer/ios/IconExplorer-tvOSTests/Info.plist, Examples/IconExplorer/ios/IconExplorer.xcodeproj/project.pbxproj, Examples/IconExplorer/ios/IconExplorer.xcodeproj/xcshareddata/xcschemes/IconExplorer-tvOS.xcscheme, Examples/IconExplorer/ios/IconExplorer/AppDelegate.h, Examples/IconExplorer/ios/IconExplorer/AppDelegate.m, Examples/IconExplorer/ios/IconExplorer/main.m, Examples/IconExplorer/ios/IconExplorerTests/IconExplorerTests.m, Examples/IconExplorer/metro.config.js, Examples/IconExplorer/package.json, Examples/IconExplorer/yarn.lock
Upgrade react-native to v0.59.5
=> Update IconExplorer example

README.md
The `NavigatorIOS` is deprecated
=> remove NavigatorIOS reference

README.md
As a react-native newbie, that section wasn't clear.
That article was super helpful
=> Add xcode article link

README.md, lib/toolbar-android.js, package.json, yarn.lock
Issue: [ToolbarAndroid Removed From RN 0.61](https://github.com/oblador/react-native-vector-icons/issues/1104)
=> Toolbar android import from react-native-community/toolbar-android

Examples/IconExplorer/android/app/build.gradle, README.md
- updated url for the react-native document
- changed url for the toolbar android to the community package
=> docs: update document url

README.md
Forgot to add Fontisto because of what the application falls.
=> Update README.md - Add Fontisto

Examples/IconExplorer/package.json, Examples/IconExplorer/src/IconSetList.js, Examples/IconExplorer/yarn.lock, lib/create-icon-set.js
This was added to fix #9 way back, but doesn't seems to be needed anymore, also is not supported in new architecture. Added an animation example too to verify this also doesn't need it.
=> Remove setNativeProps

lib/create-multi-style-icon-set.js
Added getImageSourceSync method to create-multi-style-icon-set.js file. Fixes: #1315
=> Added getImageSourceSync method, fixes #1315

README.md
Without this small change the Android app will not compile
=> 📃 update README (android setup)

directory/public/index.html
=> Added Meta description tag for improved SEO

RNVectorIcons.podspec
An unintended regression introduced in #1550
Fixes #1570
=> Fix iOS build for react-native <= 0.70

directory/src/App.css, directory/src/App.js
Adding a list of Icon Families to navigate fastly between families
=> feat: Add Family Link List on Header

README.md
There are lots of bugs around this issue
=> Add @expo/vector-icons trouble shooting

README.md
This PR fixes a typo in the README, Testing section.
Currently the last code block isn't closed, so it groups the Changelog and License blocks as they were code.
Thanks for this great library!
=> chore: fix closing code block

package.json, pnpm-lock.yaml
on current master, running `pnpm install` gives me
```
│  NX   workspaceContext.multiGlob is not a function
└─ Failed in 1.2s at /Users/vojta/_dev/react-native-vector-icons
```
updating helps
=> chore: update nx
