README.md, package.json
Hi @oblador! 
I'd like to see your lib supporting `rnpm link`, so I've added `rnpm` config block to package.json file with only one option inside - assets. By adding `assets: ["Fonts"]` we're telling `rnpm` to copy react-native-vector-icons assets into project's assets folder. Also, I've updated README file to tell rnpm users that your lib can be linked automatically.
Let me know if you have any questions!
=> Support rnpm

lib/create-icon-set.js
My fix for issue #94. Making `updateIconSources()` take a `props` param, which is `this.props` in `componentWillMount()` and `nextProps` in `componentWillReceiveProps()`.
=> Fix for TabBarIcon issue when receiving new props

README.md
@oblador It looks like the file MainActivity.java has changed in RN 0.18 and the docs are not valid anymore.
=> Docs updated for RN 0.18+ (Android)

README.md, fonts.gradle
Adds a gradle script which will copy fonts automatically when building. Can be used as follows:
```gradle
project.ext.vectoricons = [
iconFontNames: [ 'MaterialIcons.ttf', 'EvilIcons.ttf' ]
]
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
```
Sorry. Wanted to send this PR earlier (https://github.com/oblador/react-native-vector-icons/issues/65#issuecomment-165208660), but my script was not generic enough back then.
=> Add gradle script to copy fonts

RNIMigration.js
Including react from react-native is a breaking change in v0.26.0.
See: https://github.com/facebook/react-native/releases/tag/v0.26.0
=> Avoid including react from react-native

README.md
Hi,
I’ve just installed react-native-vector-icons on a newly created React-native (v0.29) project. I’m not sure if the generated configuration was modified recently but I least for my case the `getPackages` method was available in `MainApplication.java` instead of `MainActivity.java`.
=> Fix a file name in the install instructions

fonts.gradle
Tested the following scenarios:
1. Product flavor specified, e.g. - `devDebug` and `devRelease`
2. No product flavor specified e.g. - `debug` and `release`
You cans specify the variant using the `--variant` flag, e.g. - `react-native run-android --variant=devDebug`
=> Fix copying fonts when product flavor specifie

lib/generate-icon-set-from-css.js
Such as https://materialdesignicons.com/
=> Sometimes the hex character escape in content: is uppercase

README.md
When you apply : "../../node_modules/react-native-vector-icons/fonts.gradle" to android/build.gradle instead of android/app/buid.gradle, it fails to build, as in issue https://github.com/oblador/react-native-vector-icons/issues/215.
This is an easy mistake to make since I was editing this in Sublime and searched for file using command palette.
I also have no prior Android experience, so I did not expect many `build.gradle` files :)
In android/app/buid.gradle works perfectly fine.
I added a small warning. I know it's low-tech.
=> README warning against wrong build.gradle

Examples/TabBarExample/index.ios.js, README.md, lib/tab-bar-item-ios.js
First draft for adding custom colors to the tabbar icons. Based on the changes one would use it in the following way (note the use of 'renderAsOriginal').
The example uses the Icon "users" from the Entypo iconset in two different colors.
```
import Icon from 'react-native-vector-icons/Entypo'
<Icon.TabBarItemIOS
iconName='users'
selectedIconName='users'
iconColor='#ffffff'
selectedIconColor='#000000'
renderAsOriginal={true} />
```
Reason for the fix is due to the default grey template color being used otherwise. First time making a pull request so comments and/or help would be greatly appreciated!
=> added support for icon color @ tabbar

Examples/IconExplorer/android/app/src/main/AndroidManifest.xml
The app would crash and I saw the error described [here](https://github.com/facebook/react-native/issues/8215
) in the logs.
I've added `android:name` for `application` in the manifest file and that seemed to have solved the problem.
=> Fix IconExplorer for Android by adding application android:name to AndroidMainfest

template/iconSet.tpl
I changed the default template to include the node module rather than the relative path to the lib folder.
Most of the times a new icon set will be generated and import this way.
=> The import in the template should not be relative

Examples/IconExplorer/package.json, Examples/TabBarExample/package.json, RNVectorIconsManager/RNVectorIconsManager.h, RNVectorIconsManager/RNVectorIconsManager.m
React native has made a breaking change to header paths in 0.40.0 (https://github.com/facebook/react-native/releases/tag/v0.40.0)
So, it should fix this issue: #373
=> Update for RN@0.40.0 new header paths

lib/generate-icon-set-from-css.js
For example .icon-search:before {content:'🔎'}
=> Accept content specified as actual character when generating icon set from css

RNIMigration.js, directory/src/App.js, lib/create-icon-set.js, lib/icon-button.js, lib/tab-bar-item-ios.js, lib/toolbar-android.js, package.json
Replace deprecated usage of ```React.PropTypes``` by ```PropTypes``` from the ```prop-types``` package.
=> Replace React.PropTypes by prop-types

Examples/IconExplorer/index.android.js, Examples/IconExplorer/package.json
Android explorer examples are throwing an error : 
**Navigator is deprecated and has been removed from this package. It can now be installed and imported from react-native-deprecated-custom-components instead of react-native. Learn about alternative navigation solutions at http://facebook.github.io/react-native/docs/navigation.html**
The Navigator is no longer part of `react-native` package and it's recommended now to use one of the community navigations, but at this point it would require more changes in the project so the simple fix is to use the 'react-native-deprecated-custom-components'. 
Sources: 
https://www.npmjs.com/package/react-native-deprecated-custom-components
https://github.com/facebookarchive/react-native-custom-components
Tested locally and works without any problems. Let …
=> Fixed deprecated Navigator usage in Android Icon Explorer example.

lib/create-icon-set.js, lib/icon-button.js, lib/tab-bar-item-ios.js, lib/toolbar-android.js
Allow color prop to be a number, eg. (hex) `0xffee88` for opaque colors or `0x0000007f` for a transparent color.
The number can be non-hex, eg. `16772744` which is the same as `0xffee88`, but it is not as easy to read.
The reason for this support is because 'black' as a color is a lookup in a table to covert it to the number 0 (zero), and '#000000' or '#000' issues a string parser via a regex to convert to the exact same number - 0 (zero)! Same goes for any other color.
Behind the scenes react-native converts '#ffee88' to 16772744, but it is a few more checks,  computations and conversions. Keep in mind that `0xffee88` does not get "converted" to 16772744, since they are the same number, but written in different base. Internally, JavaScript interprets it as the exact same thing - a …
=> Add support for color prop as number

README.md, lib/create-icon-set.js
When using mixed icon sets in one project (e.g `MaterialIcons` and `MaterialCommunityIcons`) sometime you want to create an uniformed interface for easier use. (e.g `MaterialCommunityIcons` as fallback set).
Currently we don't have an API to check if some name is valid for one icon set. So I build the static util method `hasIcon` for this.
=> Add hasIcon static method API

android/build.gradle
Instead of assuming the `compileSdkVersion`, `targetSdkVersion`, etc, read it from the root project.
Default `compileSdkVersion` and `targetSdkVersion` to the latest versions.
Android Target API Level 26 will be required in August 2018.
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html
And the React Native team is already working on this:
facebook/react-native#17741
facebook/react-native#18095
=> Using SDK Version variables from root project

RNVectorIcons.xcodeproj/project.pbxproj
This simply reinstates @cmcewen's tvOS build target commit. 
It looks like the issues caused with `react-native link` have now been fixed at their end (facebook/react-native#13783) so it'd be useful to have this back in the library!
=> Re-add tvOS target

README.md
Updated readme so `react-native link` points to this specific package
=> react-native link now points to this specific pkg

README.md
I had some trouble getting custom icons to work on android. After reviewing the docs and multiple issues where others had a similar problem, I've updated the readme to hopefully prevent future confusion. 
- clarify `fontFile` argument
- provide example of custom font usage with android support
Thanks for your consideration and your work on this module!
=> clarifying custom font usage

lib/ensure-native-module-available.js
Require Cycle: create-icon-set.js<->ensure-native-module-available.js
=> remove require cycle warning in React Native 0.57

RNVectorIcons.podspec
Thank you for a great library.
I found a warning on iOS, so I fixed it.
NOTE: Platform version in React.podspec is iOS9.0+.
https://github.com/facebook/react-native/blob/0926373c9f6e5191fe2253534576ea8a9fd3c7ab/React.podspec#L41
=> fix platform version in podspec

package.json
Apparently babel 7 doesn't preserve it so for now lets run it twice instead as a hotfix.  Fixes #859
=> Preserve directory structure in babel build

fonts.gradle
From Android Gradle Plugin 3.2+, The assets directory has been changed from `build/intermediates/assets` to `build/intermediates/merged_assets`.
With this patch, we no longer need to copy the fonts into `android/app/src/main/assets/fonts`.
Inspired by https://github.com/facebook/react-native/pull/21408
=> Fix compatible problem with Android Gradle Plugin

README.md
The SimpleLineIcons website goes down more often than necessary, as such a new website has been made using github's hosting:
https://simplelineicons.github.io/
I have updated the link in the README.md file.
=> Updated SimpleLineIcons link in README to a github hosted link

fonts.gradle
The changes in #871 have caused issues when using older versions of the Android Gradle Plugin, i.e. 3.1.x which is used by default with React Native.  This is reported in #904 and also #661 
With 3.1.x, the current approach doesn't copy any of the font files specified.
This change creates two separate tasks, one to copy to the 3.1.X compatible path and one to copy for the 3.2.x compatible path.
I've tested with both 3.1.4 and 3.2.0 of the Android Gradle Plugin and both work with the applied change.
=> Fix issues with #871 when using Android Gradle Plugin 3.1

directory/src/App.css, directory/src/App.js
- Made the header look more unified with the search bar.
- Tweaked the searchbar design, 
- Section titles stand out more. This is useful when you're quickly scrolling down the site. The titles get lost in the current design due to small font.
=> Cleaned up the directory design.

README.md
--save flag is no longer needed to install npm packages.
=> --save flag is no longer needed

android/src/main/java/com/oblador/vectoricons/VectorIconsModule.java
Android change: Instead of generating an image with getTextBounds (which will create an image according to the character size), it is using the passed size + getFontMetrics to get spacing as well. 
The image will be the same as the imported svg in the font, when you use the Icon class in js and when you generate image for iOS.
=> Update VectorIconsModule.java to fix size/spacing generated image

bin/generate-flow.js
In my case, I have some wrappers for `Icon`; it'd be really nice to be able to re-use the available icon names there.
This change allows me to `import Ionicons, {type IoniconsGlyphs} from 'react-native-vector-icons/Ionicons'`, and automatically stay up to date with icon changes from this package.
=> Export generated flow type enum for iconsets

lib/create-icon-set-from-fontawesome5.js, package.json
Only using additional style on iOS since it breaks on non-iOS platforms (at least Android but others also seems to use font file instead fo font family when selecting fonts). Fixes #964.
Also updates package.json for new release.
=> FontAwesome 5 fix for Android

lib/create-icon-set-from-fontawesome5.js
Use `Brands` for Android and `Regular` for rest. 
Closes #983.
=> make FA5 brand icons work on Android 

fonts.gradle
Starting from Gradle Plugin 3.4+, the merged assets directory changed once again stripping out the target name.
=> Add a workaround for the new asset directory

RNVectorIcons.podspec
RN Vector Icons works perfectly on tvOS and all it needs is a podspec target
=> add tvOS target to podspec

lib/react-native.web.js
Exporting `react-native-web` via path causes StyleSheet to be instantiated twice and hence creates unreliable styles. See: https://github.com/necolas/react-native-web/issues/1367
=> fix: avoid exporting via unreliable path

react-native.config.js
React Native 0.60 is right behind the corner and it comes with latest CLI that now expects the RN config to live in `react-native.config.js`, while `"rnpm"` gets deprecated. Here's the docs on [dependencies](https://github.com/react-native-community/cli/blob/master/docs/dependencies.md) which in CLI terms are libraries like this one.
I'm not removing `"rnpm"` entry for now, since I'm not sure if you plan to support multiple RN versions with a single version of vector-icons) and they can happily live next to each other. Feel free to remove it later though :)
=> feat: add `react-native.config.js` for RN 0.60 compat

package.json
**Problem:**
react-native show the warning of using deprecated `rnpm` command in package.json. 
**What has been changed:**
This project already uses react-native.config.js, so `rnpm` was removed from package.json
=> Improvement: removed depcreated rnpm

android/build.gradle
- Loaded Android Gradle Plugin conditionally
This wraps the Android Gradle plugin dependency in the buildscripts section of android/build.gradle in a conditional:
```
if (project == rootProject) {
// ... (dependency here)
}
```
The Android Gradle plugin is only required when opening the project stand-alone, not when it is included as a dependency. By doing this, the project opens correctly in Android Studio, and it can also be consumed as a native module dependency from an application project without affecting the app project (avoiding unnecessary downloads/conflicts/etc).
for more info, you can refer to [this thread](https://github.com/facebook/react-native/pull/25569) and especially [this comment.](https://github.com/facebook/react-native/pull/25569#issuecomment-532504277)
- fixed some …
=> Loaded Android Gradle Plugin conditionally

README.md
Since rnpm support was removed in #1122, I believe `rnpm` instructions on README can also be removed.
=> remove `rnpm` instructions from README

FONTAWESOME5.md, bin/fa5-upgrade.sh
Creates a `react-native.config.js` instead of modifying `package.json` to autolink the pro fonts. Also allows setting a custom local destination folder.
=> FontAwesome 5 Pro autolinking

RNVectorIconsManager/RNVectorIconsManager.m
I tried to use icons for my Mac Catalyst target, but get "Failed to write rendered icon image" error.
This is due to the error from the line 
```objc
return [imageData writeToFile:filePath atomically:YES];
```
in function `createAndSaveGlyphImage` and the filePath is composed with `NSHomeDirectory` and `tmp`.
It turned out `NSHomeDirectory` is
- `/Users/username/Library/Containers/com.example.app/Data/` in macOS
- `/private/var/mobile/Containers/Data/Application/5AAAAAA-AAAA-AAAA-AAAA-AAAAAAA/` in iOS
In iOS, `NSHomeDirectory/tmp` exists naturally and is also known as `NSTemporaryDirectory`, while on mac `NSHomeDirectory/tmp` does not exist and we need to create the `tmp` first in order to write data.
In short, I just change `NSHomeDirectory/tmp` to `NSTemporaryDirectory` to solve the …
=> [Mac Catalyst compatibility] Fix temporary directory for icon images

RNVectorIconsManager/RNVectorIconsManager.m
=> Use full glyph as filename for getImageSource

lib/create-icon-set.js, lib/icon-button.js, lib/tab-bar-item-ios.js
As outlined in #1240, passing platform specific color types causes useless warnings, and using the proper type would break backwards compatibility with older versions of react-native. So instead this PR changes the color prop types to just accept any value, and rely on the style validation instead.
=> Accept any type for color prop

RNVectorIcons.podspec
Latest Xcode 12 fails to build without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
=> fix: Xcode 12 compatibility

package.json, yarn.lock
Yargs 16.1.1 resolves y18n vulnerability that was fixed in y18n 5.0.5 (attached commit below)
Reference: https://snyk.io/vuln/SNYK-JS-Y18N-1021887
yargs/yargs@ae001f3#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519
=> Bump Yargs to 16.1.1 

fonts.gradle
Hi there! Thanks so much for this module, @oblador, I've been using it quite a while.
I noticed in #1265 that Android Gradle Plugin 4.1 broke the font copy gradle task, similar to the way [react-native bundle copy had to be altered ](https://github.com/facebook/react-native/pull/30177) to support that version 
I had time to look at their bundle copy and updated the font copy here to more closely match their script's copy task: https://github.com/facebook/react-native/blob/c76070412fccdaa82bf4af3c94809d04ae71777e/react.gradle#L282-L317
Previously I was not able to see my react-native-vector-icons in the APK in release mode with android gradle plugin 4.1 but with these changes I can now see them. It should be backwards compatible as well and my build uses flavors and ABI splits so those …
=> fix(android): refactor font copy / support android gradle plugin 4.1+

README.md
Giving more clarification for auto-linking. The user doesn't need to update `MainApplication.java` file if the auto-linking supports it. 
This can cause unexpected error if someone is new in react-native environment,
=> React Native Auto Linking Details

README.md, react-native.config.js
CLI version 8 removed the `react-native link` command https://github.com/react-native-community/cli/pull/1537 which breaks this library. This PR removes configuration and documentation related to it.
=> Fix autolinking with React Native 0.69

fonts.gradle
Since Gradle 8 (the default as of React Native 0.72), the task dependency resolution appears to be a lot tighter, and so attempting to run:
npx react-native build-android --tasks assembleRelease
errors out with the following:
- Gradle detected a problem with the following location: '<project>/android/app/build/intermediates/ReactNativeVectorIcons'.
Reason: Task ':app:lintVitalAnalyzeRelease' uses this output of task ':app:copyReactNativeVectorIconFonts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Possible solutions:
1. Declare task ':app:copyReactNativeVectorIconFonts' as an input of ':app:lintVitalAnalyzeRelease'.
2. Declare an explicit dependency on …
=> fix: make `lintVitalAnalyze*` depend on copy

lib/NativeRNVectorIcons.web.js
The recent new arch changes broke things for React Native Web.
The web team have indicated that they won't be mocking out TurboModuleRegistry themselves and preference downstream libraries supporting the web. (https://github.com/necolas/react-native-web/pull/2503#issuecomment-1485550206)
=> Fix to get working with react-native-web

README.md
`tabBarOptions` is deprecated in [react navigation](https://reactnavigation.org/docs/tab-based-navigation).
=> Replace tabBarOptions with screenOptions

RNVectorIconsManager/RNVectorIconsManager.m
fixes: #1465 
---
There might be a root cause here somewhere, but it looks like the error I'm seeing is the duplicate name. Which I assume is an iteration of already registered.
=> fix (ios): support kCTFontManagerErrorDuplicatedName as allowable error

README.md
Just spent a few hours trying to understand why my icons where not showing on Android after changing to a monorepo.
This issue https://github.com/oblador/react-native-vector-icons/issues/1183 requests that the docs be updated to mention the extra config necessary for RNVI to work well in a monorepo.
This PR addresses exactly this.
fixes: https://github.com/oblador/react-native-vector-icons/issues/1183
fixes: https://github.com/oblador/react-native-vector-icons/issues/1117
Please let me know if anything is unclear or inaccurate.
✌️
=> Update README with monorepo info for Android

RNVectorIconsManager/RNVectorIconsManager.m
Hello, I was troubleshooting some console errors which were showing up while upgrading my react-native version at work and felt like this would be a useful addition to the library. Please take a look.
Thank you!
--
Improve error logging for failed font imports by including the missing fonts name in the error message. Current exception message is not detailed enough to help developers troubleshoot which exact font is failing without jumping from debugging JS --> Objective C code.
=> Improve Error Logging for Font Imports

directory/bin/generate-font-styles.js, directory/bin/generate-glyphmap-index.js, directory/src/App.js
What's the problem:
Library website with icons list stop rendering due an error on render method.
How i resolved:
The problem is the script that generates the glyphmaps, for some reason, the script that merge the files into one map json, is putting _meta json in too, and thats causes an exception on rendering function. I just filter the json property name if there's a family with "_meta" in the name. Probaly the script should be fixed, but I don't know exactly how things work here, so it's a quick solution.
=> fix: filter meta font json from render method

RNVectorIconsManager/RNVectorIconsManager.mm
Released errorRef object which is not managed by ARC to fix memory leak
Xcode 14.3, iOS 16.4 
https://github.com/oblador/react-native-vector-icons/issues/1499
Into `loadFontWithFileName` func we call CTFontManagerRegisterGraphicsFont whitch have parameter with type  CFErrorRef * which is not managed by ARC. 
Proposed fix in RNVectorIconsManager.m:
To avoid memory leak we need to release that errorRef varible after usage.
```
RCT_EXPORT_METHOD(loadFontWithFileName:(NSString *)fontFileName
extension:(NSString *)extension
resolver:(RCTPromiseResolveBlock)resolve
rejecter:(RCTPromiseRejectBlock)reject)
{
NSBundle *bundle = [NSBundle bundleForClass:[self class]];
NSURL *fontURL = [bundle URLForResource:fontFileName withExtension:extension];
NSData *fontData = [NSData …
```
=> Fix for Memory Leak. iOS. RNVectorIconsManager

fonts.gradle
Fix build errors on react native 0.73.x version.
This is similar to a previous fix done for 0.72
https://github.com/oblador/react-native-vector-icons/issues/1508#issuecomment-1606108215
Commit details: https://github.com/oblador/react-native-vector-icons/commit/e9cc5898a4331f5f9b9e03e3f5345c5cda3ebf61
=> fix(fonts.gradle): fix react native 0.73 build errors

README.md
This is a docs-only change.
We add instructions on how to configure the font-families for a React-App so the font-glyphs can be found when using RNVI with React and webpack (for example).
We additionally add a troubleshooting section to explain how to support `unsupported JSX` errors when using webpack with RNVI.
=> docs: add docs for how to use RNVI with react-native-web

RNVectorIcons.podspec
This PR adds support for vision os
https://github.com/oblador/react-native-vector-icons/assets/42144106/5ecb6a8a-6f04-4a75-9c94-ab3f8b7c9042
Test plan:
1. create new visionos app using `npx @callstack/react-native-visionos init MyApp`
2. add react-native-vector-icons
3. Test if it works
=> added visionos support

packages/common/android/build.gradle
Currently, building an Android App with the `@react-native-vector-icons/common` `0.0.1-alpha.6` package installed fails with the following error if no icon package is installed:
```
Execution failed for task ':react-native-vector-icons_common:copyFonts'.
> path may not be null or empty string. path=''
```
This PR filters out empty strings in `build.gradle`'s `copyFonts` task, which fixes the issue.
=> Fixes monorepo Android Build if only `@react-native-vector-icons/common` is Installed

packages/icon-explorer/android/build.gradle
With this PRs icon-explorer should be buildable and testable with detox on android in monorepo branch
- set testBuildType in androidExtension directly (without this androidTest will only build debug so it need to set testBinaryPath)
=> fix(icon-explorer@android): make android build work with detox

README.md
Hi and thanks for maintaining this popular library!
This PR attempts to clear up the installation instructions for iOS.
The instructions currently say that a [manual step is needed](https://github.com/oblador/react-native-vector-icons?tab=readme-ov-file#ios-setup), but I haven't found it to be necessary. In fact, when I follow the "iOS Setup" I get an error `Multiple commands produce '.../iconsdemo.app/FontAwesome6_Regular.ttf'` 
Only the last bullet point mentions that if you use autolinking (which almost everybody does), it will automatically add all fonts - so the manual adding of files to Xcode isn't needed.
Then there's this:
> Note 2: If you're getting problems with duplicate outputs file for fonts on ios build, try running cd ios && pod install after the react-native.config.js …
=> docs: remove unnecessary ios install steps

README.md
For iOS it was crucial for me to run a "pod update" in the /ios folder to propagate the changes to the Info.plist and the addition of the fonts. The app could not find the fonts otherwise.
The README does not mention this, I had to look around to find instructions on other sites providing this info.
=> README: add info regarding 'pod update' necessary for iOS

packages/fontawesome-common/generators/app/templates/src/index.tsx, packages/fontawesome5-pro/src/index.tsx, packages/fontawesome5/src/index.tsx, packages/fontawesome6-pro/src/index.tsx, packages/fontawesome6/src/index.tsx
Previously, validation only ran when an iconStyle was specified.
This adds validation for the default iconStyle, ensuring it runs even when no specific style is provided.
For Example "truck" icon in fontawesome5 doesn't exist in regular and only solid.
=> fix: warn if glyph does not exist for default IconStyle.

README.md, packages/common/src/dynamicLoading/dynamic-font-loading.ts, packages/common/src/dynamicLoading/dynamic-loading-setting.ts
This PR increases strictness of checks of expo modules upon the `globalThis.expo`.
Also, it removes deep import of `react-native/Libraries/Image/resolveAssetSource` from react native because it will soon not be allowed: https://github.com/react-native-community/discussions-and-proposals/pull/894
There are no changes in the runtime behavior.
Built the common package locally and installed it into a fresh expo go project. Rendering of icons worked.
that being said, I had to do some workarounds to get `pnpm install` to finish successfully:
```
 ERR_PNPM_FETCH_401  GET https://npm.fontawesome.com/@fortawesome/fontawesome-free/-/fontawesome-free-5.15.4.tgz: Unauthorized - 401
No authorization header was set for the request.
```
Maybe I just missed some docs but at the first sight, this seems to …
=> refactor: stricter Expo compatibility checks

packages/ant-design/android/build.gradle, packages/entypo/android/build.gradle, packages/evil-icons/android/build.gradle, packages/feather/android/build.gradle, packages/fontawesome/android/build.gradle, packages/fontawesome5-pro/android/build.gradle, packages/fontawesome5/android/build.gradle, packages/fontawesome6-pro/android/build.gradle, packages/fontawesome6/android/build.gradle, packages/fontello/android/build.gradle, packages/fontisto/android/build.gradle, packages/foundation/android/build.gradle, packages/generator-react-native-vector-icons/src/app/templates/android/build.gradle, packages/icomoon/android/build.gradle, packages/ionicons/android/build.gradle, packages/lucide/android/build.gradle, packages/material-design-icons/android/build.gradle, packages/material-icons/android/build.gradle, packages/octicons/android/build.gradle, packages/simple-line-icons/android/build.gradle, packages/zocial/android/build.gradle
Try to use root project's compileSdk, and fallback to ours instead of only using ours, which causes aar incompatibility with some libraries. 
This is done to avoid the following errors:
```
Execution failed for task ':react-native-vector-icons_material-icons:checkDebugAndroidTestAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
> 8 issues were found when checking AAR metadata:
1.  Dependency 'androidx.appcompat:appcompat-resources:1.6.1' requires libraries and applications that
depend on it to compile against version 33 or later of the
Android APIs.
```
=> fix(template): try to use root project's compile sdk to avoid aar metadata incompatablity

packages/fontawesome-common/bin/fa-upgrade, packages/fontawesome5-pro/README.md, packages/fontawesome6-pro/README.md
I installed 12.0.1 version of the fontweasome6-pro pacakge. On running the `npx fa-upgrade6` command, it downloads the fonts into rnvi-fonts dir.
These fonts were not getting picked during the build process and on investigation I see that both the [gradle script](https://github.com/oblador/react-native-vector-icons/blob/master/packages/fontawesome6-pro/android/build.gradle#L67) and [podspec script](https://github.com/oblador/react-native-vector-icons/blob/master/packages/fontawesome6-pro/react-native-vector-icons-fontawesome6-pro.podspec#L50) expects the fonts to be in `rnvi-fonts/fontawesome6-pro` directory
So I modified the fa-upgrade script to append this to the destination directory path.
=> fix: put fontawesome pro fonts in the right path

packages/get-image/src/NativeVectorIcons.web.ts, packages/get-image/src/ensure-native-module-available.ts, packages/get-image/src/index.ts
With the previous impl, web users would simply get `VectorIcons.getImageForFont is not a function` which looks like a bug in this lib, or the user's setup. This explains the situation a bit better.
=> fix(web): throw a meaningful error in getImageForFont

fonts.gradle
I had an error with a build (RN 0.73, Gradle 8.3, react-native-vector-icons 10.2.0):
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem was found with the configuration of task ':app:lintAnalyzeDebug' (type 'AndroidLintAnalysisTask').
- Gradle detected a problem with the following location: '/path/to/android/app/build/intermediates/ReactNativeVectorIcons'.
Reason: Task ':app:lintAnalyzeDebug' uses this output of task ':app:copyReactNativeVectorIconFonts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Possible solutions:
1. Declare task ':app:copyReactNativeVectorIconFonts' as an input of ':app:lintAnalyzeDebug'.
2. Declare an explicit dependency on …
```
=> Fix Gradle task dependency (include lintAnalyze)

packages/ant-design/src/index.ts, packages/entypo/src/index.ts, packages/evil-icons/src/index.ts, packages/feather/src/index.ts, packages/fontawesome/src/index.ts, packages/fontisto/src/index.ts, packages/foundation/src/index.ts, packages/generator-react-native-vector-icons/src/app/templates/src/index.ts, packages/ionicons/src/index.ts, packages/lucide/src/index.ts, packages/material-design-icons/src/index.ts, packages/material-icons/src/index.ts, packages/octicons/src/index.ts, packages/simple-line-icons/src/index.ts, packages/zocial/src/index.ts
The icon components are client components and should be marked with `'use client'` directive for RSC usage.
I haven't found the right way to apply the change from the template file to the individual packages; there's the standard `CONTRBUTING` file but also `docs/DEVELOPMENT` which seems like they should be merged into one (?) - probably the `CONTRBUTING` file which is a the expected place to find this stuff.
=> feat: add 'use client' directive for RSC

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/workflows/issue-handling.yml
- updated templates. Most notably the bug report template to make it more clear that repros are _required_. Removed the word "please" to make it clear that adding the information is not optional and that we're confident about what we ask, while also being polite about it.
- added automation for `missing-repro` label which will close issues with such label with a friendly message. 
_Maintainers don't have time to fiddle around with issues where it's unclear how to reproduce them; this ensures maintainers' time is well-spent. It's better for issue reporters too because having a repro helps immensely with providing a fix._
=> chore: update templates, close issues by label

packages/codemod/src/checkGitStatus.ts, packages/codemod/src/expo/import-transform.ts, packages/codemod/src/expo/package-json.ts, packages/codemod/src/index.ts
- check git status before running the codemod
- install vector icon packages using `npx expo install` in the expo codemod
=> [codemod] add git status check, use npx expo install to add deps

CONTRIBUTING.md, packages/ant-design/package.json, packages/entypo/package.json, packages/evil-icons/package.json, packages/feather/package.json, packages/fontawesome/package.json, packages/fontawesome5-pro/package.json, packages/fontawesome5/package.json, packages/fontawesome6-pro/package.json, packages/fontawesome6/package.json, packages/fontello/package.json, packages/fontisto/package.json, packages/foundation/package.json, packages/generator-react-native-vector-icons/src/app/templates/package.json, packages/icomoon/package.json, packages/icon-explorer/src/IconList.tsx, packages/icon-explorer/src/icon-sets.tsx, packages/ionicons/package.json, packages/lucide/package.json, packages/material-design-icons/package.json, packages/material-icons/package.json, packages/octicons/package.json, packages/simple-line-icons/package.json, packages/zocial/package.json
This allows consumers to import ttf files and glyphmaps.
Importing these are valid uses cases as demonstrated by https://github.com/oblador/react-native-vector-icons/issues/1785 and by the `icon-explorer` demo app.
closes #1785, closes #1825
=> feat: export font files and glyphmaps

packages/get-image/react-native-vector-icons.podspec
`install_modules_dependencies` is available since RN 0.71 so we can just use that
=> chore: simplify get-image podspec

packages/common/src/create-icon-set.tsx, packages/common/src/index.ts, packages/fontello/README.md, packages/fontello/src/index.ts, packages/icomoon/README.md, packages/icomoon/src/index.ts
`createIconSet` from the `common` package has two supported signatures: https://github.com/oblador/react-native-vector-icons/blob/4ac93f86fd2815b8b4ba01851041d9239c26f3a8/packages/common/src/create-icon-set.tsx#L47
the second signature support dynamic font loading: https://github.com/oblador/react-native-vector-icons/blob/4ac93f86fd2815b8b4ba01851041d9239c26f3a8/packages/common/src/create-icon-set.tsx#L53
the `icoMoon` and `fontello` packages so far shipped with only the first (old) signature and this allows them to be used for dynamic loading of the custom fonts. This is especially useful in the context of Expo Go.
=> feat: support dynamic font loading in icomoon and fontello

packages/common/package.json, packages/common/src/scripts/common.ts
fix for https://github.com/oblador/react-native-vector-icons/issues/1835
see: https://nodejs.org/en/blog/release/v20.19.0
=> fix: correct required node version
